It seems like if the module dir is changed gradually then an error like
Traceback (most recent call last):
  File "/home/lucasw/tmp_catkin_ws/src/rqt_mypkg/rqt_example_py/scripts/rqt_mypkg", line 5, in <module>
    from rqt_mypkg.mypkg import MyPlugin
ImportError: No module named mypkg

results, but if that module was always renamed (clone this in a fresh catkin_ws) it will work.